### ISSUE TITLE
Split logger to stdout/stderr

### ISSUE THREAD

**Issue by berland** [equinor/pyscal#310]
Same task as performed in https://github.com/equinor/subscript/issues/196

**Comment by berland** [comment]
Better look at https://github.com/equinor/ecl2df/pull/297 since pyscal can also write output to stdout.

**Comment by ttomasbucek** [comment]
Greetings, I would like to work on this issue. It is my first issue, so can you give a little more information about the problem and assign this issue to me?

**Comment by berland** [comment]
Good! Start by looking at the two other tasks referenced here, and do the analogous thing in pyscal.

**Comment by ttomasbucek** [comment]
OK, thank you.

**Comment by ttomasbucek** [comment]
![demo](https://user-images.githubusercontent.com/63037853/137718616-d3697747-b6d8-4e53-800d-0f9c0f803728.jpg)
I made a custom script(testing_logger.py) for demonstration, which runs example code from documentation page. Now error goes to stderr and other logs to stdout. If generated output goes to stdout, then all logs are forwarded do stderr. Is this expected behavior?
